### ISSUE TITLE
pytorch: correct initialization

### ISSUE THREAD

**Issue by simra** [simra/FedNewsRec#1]
The pytorch model isn't initialized properly- need to mimic the keras initializers.

**Comment by wanglun1996** [comment]
@simra solved in commitment 9c052bb243267a862eccf12e682ae97fd7d37f2d and 516c04b2b2ae4d3142fe502629b840dfc816a2d5; please check the correctness and let me know there is any error

**Comment by simra** [comment]
Thanks @wanglun1996 I merged your changes. I also did some testing on the AttentivePooling class and made some small changes so now it returns almost exactly the same numerical results as the keras version.
I was hoping to do the same with the MultiHeadAttention, but where keras encodes K,Q,V matrices explicitly, pytorch applies an optimization and has only input and output projections- I've been meaning to read the paper to see how these relate to K/Q/V so I can do a side-by-side comparison.  I'll push my testing code- it's messy but might give you ideas for unit testing the other modules.

**Comment by simra** [comment]
Testing code: https://github.com/simra/FedNewsRec/blob/simra/train_setup/code/test_conversion.py

**Comment by wanglun1996** [comment]
thanks @simra. I just took a look into pytorch's implementation of MultiheadAttention. It concatenates all the K, Q, V matrices into one matrix called in_proj_weight (see here for the source code in pytorch implementation https://pytorch.org/docs/stable/_modules/torch/nn/modules/activation.html#MultiheadAttention). If you want to do the same testing for MultiheadAttention, maybe we can schedule a time for pair programming.

**Comment by simra** [comment]
I ran a job over night and it seems as though the model is slowly learning something. I've disabled weight decay and restarted to see if it progresses more efficiently- let me keep you posted and if it looks like it will reach a reasonable performance level then we can run with this model.

**Comment by wanglun1996** [comment]
thanks Robert! which weight decay did you disable?

**Comment by simra** [comment]
I had added weight decay to the SGD optimizer to prevent exploding gradients, but it hasn't really helped.  I ran a long run yesterday and we initially see an improvement in accuracy but the loss is still volatile and not really trending in any direction. So I think it will take more testing to verify that we have the model wired up correctly. Let's discuss next steps when we meet this afternoon.

**Comment by simra** [comment]
@wanglun1996 : the tensorflow attention module has no W^0 output layer- am I reading this correctly?  ie. the only trainable parameters are the Q,K,V matrices.  It might be hard to force the pytorch model to mimic its behavior.

**Comment by simra** [comment]
@wanglun1996 : ok I pushed an update to simra/train_setup that copies the TF Attention module exactly.  I'm running a training run now and I'll continue to verify the other modules.

**Comment by simra** [comment]
After 9000 clients (1500 rounds), metrics seem to be moving the right way.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/rsim/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/rsim/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



600 | 0.541688 | 0.231988 | 0.248335 | 0.30727 | 1.657515
-- | -- | -- | -- | -- | --
1200 | 0.549655 | 0.242138 | 0.253625 | 0.321061 | 1.698528
1800 | 0.564774 | 0.246446 | 0.259147 | 0.327375 | 1.465757
2400 | 0.556613 | 0.243748 | 0.25323 | 0.320122 | 1.592015
3000 | 0.553098 | 0.241241 | 0.252955 | 0.320905 | 1.38803
3600 | 0.549955 | 0.249436 | 0.258728 | 0.327764 | 1.547758
4200 | 0.559154 | 0.243002 | 0.259061 | 0.323549 | 1.576477
4800 | 0.567591 | 0.243161 | 0.257013 | 0.325815 | 1.616418
5400 | 0.553316 | 0.239466 | 0.256708 | 0.321129 | 1.460134
6000 | 0.564091 | 0.245226 | 0.261127 | 0.328227 | 1.502752
6600 | 0.553574 | 0.239967 | 0.25295 | 0.319808 | 1.599257
7200 | 0.567619 | 0.239888 | 0.258571 | 0.323561 | 1.170774
7800 | 0.582728 | 0.248178 | 0.264451 | 0.331885 | 1.681432
8400 | 0.584805 | 0.25544 | 0.273121 | 0.33743 | 1.405089
9000 | 0.582402 | 0.25255 | 0.276075 | 0.337986 | 1.549042



</body>

</html>

**Comment by simra** [comment]
I've pushed my latest changes, these numbers are using AdamW for the optimizer + a lower learning rate and weight-decay.

`python train_pt_fl.py --rounds 10001 --lr 0.01 --checkpoint 100 --lmb 0.01`

**Comment by wanglun1996** [comment]
thanks Robert! do you use AdamW for the client-side optimization or the servers-side optimization?

**Comment by wanglun1996** [comment]
@simra please correct me if I am wrong but since AdamW has local states, in each round and across rounds, the local state learned from one client will be used on the next client which seems problematic. 

How does the performance look if we just use SGD?

**Comment by simra** [comment]
You're right- I thought we were only applying the optimizer to the central update but we apply it in each local update. I'll switch back to SGD.

In any case I spoke too soon and the model couldn't maintain its performance.  The first 15 rounds or so were promising.

![image](https://user-images.githubusercontent.com/2946735/172883647-507a4a36-0463-4890-9e52-da2f06fbe409.png)

**Comment by wanglun1996** [comment]
@simra Here are the results I got using SGD and learning rate 0.3. It seems we are making progress slowly but the convergence is slower than the tf version. For convenience of comparison I also attach the tf version convergence figure.

6000    0.5313852064355502      0.22624203456506833     0.2349255907043836      0.3021036649973313      1.6851859092712402
12000   0.5377714008915888      0.23007140212529048     0.24539509623082167     0.3097047422867635      1.5203890422979989
18000   0.5208511138886701      0.2268604758502789      0.23817988565401016     0.3001591403828036      1.3722635166512596
24000   0.5556270763863516      0.23721914321433174     0.2514705826518415      0.31930801726405866     1.5751555632031151
30000   0.5761439301821342      0.24548494860341552     0.2581718598617073      0.32820134111840404     1.470998701122072
36000   0.5592801420820742      0.23901738892232557     0.25611571135979333     0.3196525624346671      1.4537225405375163
42000   0.5453115586340526      0.23703511085968465     0.24513749836294355     0.3069909971088758      1.7871593281074805
48000   0.5885932785551482      0.2565635027840842      0.2784436993268204      0.34134630838536156     1.4608998050292332
54000   0.58400314680247        0.25467517889062996     0.27514071483039887     0.3384804782086873      1.6496462722619374
60000   0.5757008494744759      0.252560835191059       0.27005075708275983     0.33101390444980755     1.4888423266013462
66000   0.5762831188668773      0.2519895930034295      0.2685359478021895      0.32993529334738675     1.6076302727063496
72000   0.5829890100004805      0.2515604383997481      0.2687638576243036      0.3351008542034445      1.5749147476321117
78000   0.5758472283366792      0.2573843891596847      0.27869172384951063     0.3387239722806096      1.56184853033887
84000   0.554874996762189       0.23523947832991993     0.2497353949414943      0.31519683982320773     1.4357822762802244
90000   0.5742968474795576      0.239060938514403       0.2565519504723688      0.32578795374021874     1.5335924458793466
96000   0.5845621581859404      0.2508976701425918      0.2686831875850725      0.332479587682641       1.362293082806799
102000  0.5790895221035307      0.24412207078443593     0.2640796139044301      0.32754539696473267     1.3574536701043447
108000  0.5682091632248054      0.24265933955898297     0.2602001324527944      0.3253448477354784      1.6069478152253833
114000  0.5983841842662938      0.25598290706942456     0.2825938501307432      0.34376989953927056     1.4974046399195988
120000  0.5658115382125678      0.241728710038808       0.263100279392274       0.3253258566465658      1.455609995788998
126000  0.5861799778616814      0.24939961759501547     0.2649405252599333      0.33444663312353634     1.5854065566072386
132000  0.5747049004767975      0.24790305058781525     0.27095390337560354     0.3325931000864585      1.5335455579890145
138000  0.5939904342449651      0.25340737789027545     0.2731382720107783      0.3401253714198338      1.7474090731333172
144000  0.5894368211355949      0.250830194491691       0.2758683659260329      0.3393454798381711      1.2933929373820623
150000  0.5841181481840582      0.25239859495759404     0.27598888422690404     0.3378529851333167      1.4785153021415074
156000  0.5903967994629248      0.2594609069140748      0.2857738672415039      0.34546308079977844     1.4680972894032795
162000  0.5996352399076931      0.264731218159762       0.28787742668176475     0.34891799138091517     1.4457813661286245
168000  0.5858973376894847      0.25362156672716585     0.2793138412631794      0.33958292957144937     1.385128257671992
174000  0.5901300493911069      0.25825555685409396     0.28218130262330604     0.34261227308628084     1.54292266759457
180000  0.592204116974287       0.25419455657449114     0.2792654580861299      0.3404703435222175      1.5200934360424678
![plot (2)](https://user-images.githubusercontent.com/14271221/172932198-a4d3a62a-baa1-4e67-abaa-7410a90fa264.png)

**Comment by simra** [comment]
Yes that looks better, I'll try a run too.  I've successfully validated AttentivePooling, Attention, and the DocEncoder.  I'll keep going for completeness but it looks to me like we have functional equivalence now.
L2 norm of the output deltas, given the same layer weights:
AttentivePooling error: 8.1617024e-08
Attention error: 1.4612131e-06
DocEncoder error: 1.7622069e-06

**Comment by simra** [comment]
@wanglun1996 how many localiters?

**Comment by wanglun1996** [comment]
@simra 1

**Comment by simra** [comment]
Not much luck getting this model to learn consistently so I'm still going through layer by layer.  I validated the TimeDistributed model, and now I'm working on the user encoder.  Unfortunately, the Keras and PT GRU implementations have subtle differences, and I haven't been able to make a PT GRU behave like Keras.  Let me know if you make any progress on this.

**Comment by simra** [comment]
Ok, I validated the GRU and UserEncoder, up to the subtle difference that Keras GRU uses a hard sigmoid for its recurrent activation, and Pytorch GRU trains a bias vector to accompany the recurrent kernel.
Last thing to check is the full model.

**Comment by simra** [comment]
I dialed down the learning rate and added a scheduler.  Learning is slow but much more stable now.  I'll experiment a little more with this over the weekend.

train_pt_fl.py --rounds 10001 --lr 0.01 --localiters 1 --lmb 0.001 --perround 10

![plot](https://user-images.githubusercontent.com/2946735/173176949-d16823ff-7aff-44ed-9e5c-0fbc12a6f515.png)

**Comment by simra** [comment]
After half an epoch:

![image](https://user-images.githubusercontent.com/2946735/173192854-c6817562-b843-4cb1-b767-cfa72c98f791.png)

**Comment by simra** [comment]
@wanglun1996 I ran some parameter sweeps to better tune the learning rate, etc.  I just measured accuracy once every 100 rounds, for 2000 rounds total, and reported the best AUC. In all cases we hit the best AUC at 2000 rounds so maybe I should run again for 4000 rounds.  Here are the best-performing parameters:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RSIM~1.RED/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RSIM~1.RED/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



gamma | lmb | lr | total_clients | auc | mrr
-- | -- | -- | -- | -- | --
0.99 | 0.0001 | 0.01 | 20000 | 0.558073 | 0.232647
0.999 | 0.0001 | 0.01 | 20000 | 0.554869 | 0.233376
1 | 0.001 | 0.01 | 20000 | 0.554543 | 0.231944
0.99 | 0.001 | 0.01 | 20000 | 0.55446 | 0.233521
0.99 | 0.01 | 0.01 | 20000 | 0.553602 | 0.236273
0.999 | 0.001 | 0.01 | 20000 | 0.553043 | 0.236182
1 | 0.0001 | 0.01 | 20000 | 0.551104 | 0.23508
1 | 0.0001 | 0.001 | 20000 | 0.549836 | 0.237086
0.999 | 0.01 | 0.01 | 20000 | 0.548462 | 0.233081
0.999 | 0.001 | 0.1 | 20000 | 0.54664 | 0.23174
0.999 | 0.001 | 0.001 | 20000 | 0.5466 | 0.226631
1 | 0.0001 | 0.1 | 20000 | 0.546292 | 0.234814
0.99 | 0.0001 | 0.001 | 20000 | 0.546124 | 0.236475
1 | 0.0001 | 0.0001 | 20000 | 0.545869 | 0.2465
1 | 0.001 | 0.1 | 20000 | 0.544425 | 0.238053
0.99 | 0.001 | 0.001 | 20000 | 0.544107 | 0.233453
1 | 0.01 | 0.01 | 20000 | 0.542957 | 0.231237
0.999 | 0.0001 | 0.1 | 20000 | 0.54156 | 0.234609
0.99 | 0.001 | 0.1 | 20000 | 0.539407 | 0.232104
0.999 | 0.01 | 0.1 | 20000 | 0.537864 | 0.233074
0.999 | 0.0001 | 0.001 | 20000 | 0.536317 | 0.234072
1 | 0.01 | 0.1 | 20000 | 0.535896 | 0.232215
0.99 | 0.01 | 0.001 | 20000 | 0.535086 | 0.227735
0.99 | 0.0001 | 0.1 | 20000 | 0.530717 | 0.230629
1 | 0.001 | 0.001 | 20000 | 0.530682 | 0.228604
0.99 | 0.01 | 0.1 | 20000 | 0.528989 | 0.234544
0.99 | 0.0001 | 0.0001 | 20000 | 0.526778 | 0.22835
1 | 0.01 | 0.001 | 20000 | 0.525642 | 0.226026
0.999 | 0.01 | 0.0001 | 20000 | 0.521613 | 0.224206
0.999 | 0.01 | 0.001 | 20000 | 0.520781 | 0.232486
0.999 | 0.0001 | 0.0001 | 20000 | 0.519812 | 0.232199
1 | 0.001 | 0.0001 | 20000 | 0.513639 | 0.223137
0.999 | 0.001 | 0.0001 | 20000 | 0.500737 | 0.212425
1 | 0.01 | 0.0001 | 20000 | 0.494851 | 0.224049
0.99 | 0.01 | 0.0001 | 20000 | 0.489115 | 0.216292
0.99 | 0.001 | 0.0001 | 20000 | 0.480705 | 0.213722



</body>

</html>

**Comment by simra** [comment]
I've merged all my code into main. Maybe for next steps we could add Gaussian DP?

**Comment by wanglun1996** [comment]
thanks @simra! the performance after sampling 20000 clients seem to comply with the tf version. Have we ever reached the peak performance like the tf version after 140000 clients?

I will add Gaussian mechanism with RDP accountant to our code tomorrow. Also I am not sure if RDP accountant is still the best privacy accountant today but I remember Sergey's and Yuxiang's group separately developed more advanced composition techniques. Might need to look into this a little bit.

**Comment by simra** [comment]
Here's the fancy accountant from Sergey's group: https://github.com/microsoft/prv_accountant

I only ran to 20k clients so the experiments would be fast- I'll run a longer experiment on a smaller subset of hyperparameters now.

**Comment by wanglun1996** [comment]
Hi @simra, I just found a bug in the training loop. model.state_dict() returns a shallow copy of the model's parameters so except the first sample's update, all the other samples' updates are not actually used. This is the culprit of our slow convergence. I just fixed this and achieved below performance with 2000 rounds. Much better than the old results we have. I am now running with larger number of rounds.

12000   0.5607850243502568      0.24634042240731385     0.26201930515134236     0.32692679516166845     1.3485028266699777

Also I just added central Gaussian mechanism. Have not got a chance to thoroughly test it yet. I will start to play with different privacy parameters after finishing the above non-private experiments.

**Comment by wanglun1996** [comment]
@simra after more rounds the convergence stops at AUC of 0.56. I guess it is because the scheduler reduces the learning rate by too much. I have disabled the scheduler and rerun the experiments with learning rate 0.3 as used in the tf version.

**Comment by wanglun1996** [comment]
@simra seems we finally get the same convergence performance as the tf version. The code is in the latest PR.

6000    0.5511975664764912      0.24451676664153835     0.26005597659020346     0.32369371479725784     1.219303262564871
12000   0.5716636473762373      0.24805794446979965     0.27082076536973837     0.33154195134045095     1.5059671766228144
18000   0.5793770279444151      0.24522922065311592     0.26737830077040325     0.33229810816599203     1.8678820170462132
24000   0.5983252858295843      0.2623648466748113      0.2878119207592136      0.34905560570537936     1.560082725904606
30000   0.591601323549118       0.2622432381521404      0.2895556540174343      0.3497347062402923      1.4042298060324458
36000   0.590044533457735       0.25564991533550474     0.2786245910060355      0.3422477460161369      1.5110692249404059
42000   0.5748329910936859      0.25229946921936225     0.27092936941344514     0.3351167999929666      1.4891954947085608
48000   0.5985588422679053      0.256426173380069       0.2844448438581683      0.34769119125236303     1.520004440099001
54000   0.6070928165296814      0.26651090282632967     0.290768885358734       0.35515235591364736     1.0805662880341211
60000   0.6045478230547309      0.26820269548057907     0.29086800361843995     0.355507285638307       1.4689079473416011
66000   0.616968175241015       0.27569824368274143     0.30116329833643807     0.36574131605454735     1.6166895257102116
72000   0.6125271266791341      0.2710063434633519      0.2948117433174094      0.3608200039134682      1.2721042610109432
78000   0.6201803645782481      0.27588704932207236     0.3003729592647259      0.36635636965024754     1.1900237898031871
84000   0.6247481075448504      0.2815023116333822      0.3072537471202929      0.3707889394194713      1.337839961051941
90000   0.6359946237016435      0.2927876760972658      0.32217467436680863     0.3848736033264273      1.1653428991635641
96000   0.6317435801799848      0.2913234081766487      0.3180266519075015      0.3814675734668337      1.2604874300735969
102000  0.6413240864310119      0.29943709112200784     0.32857345118726455     0.39021651329434065     1.3616671030720076
108000  0.6427538352590988      0.29829027599666935     0.3250406172366694      0.3899332758705454      1.7680053401876379
114000  0.6392314792184545      0.29612928464723987     0.32327101026180677     0.3863416000471069      1.0422353907149298
120000  0.6336498528756754      0.29079322281658737     0.31696872711914853     0.3805787013799462      1.3920832126150053
126000  0.6529693030733946      0.3018570486523157      0.33002292174037545     0.3934365001742582      1.498634435236454
132000  0.6432249848890867      0.29619460490328064     0.32638375138964903     0.38910592940185207     1.669468172929353
138000  0.6511401506413095      0.3046073828703694      0.3376537805327269      0.39809297815803846     1.4006966055267387
144000  0.6495179275379258      0.30017604048781804     0.330297594105044       0.39403001967520723     1.5256518649749269
150000  0.6499496011063252      0.3018779653514904      0.3318074287364713      0.39459770452654874     1.2065037270387016
156000  0.6435854389217058      0.2956328067439061      0.32264417843739235     0.38757983613792174     1.469824425379435
162000  0.6488541731765841      0.3000317565484283      0.33056993927656314     0.3935067384738341      1.2352461505740406
168000  0.6514013544955235      0.301818375612375       0.3306866340222547      0.3937862488841189      1.3228628007751524
174000  0.648146123141411       0.3004623289151698      0.33008262398669286     0.3918260650457559      1.4350642522176107
180000  0.6559592614862781      0.3040988940538842      0.3354504071291505      0.39828037030850905     1.3842092615862687
![Picture1](https://user-images.githubusercontent.com/14271221/174897044-58af3c1b-20e2-4cbe-b7c1-741a8a43d1a4.png)

**Comment by wanglun1996** [comment]
Issue closed as the issue has been solved.
